### ISSUE TITLE
[STH] /usr/sth/conf/sth_default.conf does not match with /usr/sth/config.js

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-sth-comet#130] opened 2015-06-09 11:13 UTC
We have seen that /usr/sth/conf/sth_default.conf is not updated when /usr/sth/config.js is modified.

**Comment by gtorodelvalle** [comment] 2015-06-09 13:14
In fact, is `sth_default.conf` really needed any longer once we have the `config.js` file? :)

**Comment by vgarciag** [comment] 2015-06-09 13:39
The file `sth_default.conf` should be kept because is the _template_ to configure STH in multi-instance mode, this file is the base file to configure two or more services using copy&paste _pattern_. 

The problem is the possible misalignment between `sth_default.conf` and `config.js` so, @gtorodelvalle, keep in mind: when you touch `config.js` remember to modify `sth_default.conf` also.

**Comment by iariasleon** [comment] 2015-06-09 14:38
maintain two configuration files is a great source of possible errors

**Comment by gtorodelvalle** [comment] 2015-06-09 15:22
He, he... ;) You bet! ;) Thanks @vgarciag !

**Comment by gtorodelvalle** [comment] 2015-06-10 08:15
As mentioned in Skype, we do have 2 ways of configuring the server as stated in https://github.com/telefonicaid/IoT-STH/tree/release/0.1.0#running-the-sth-server to ease its configuration when the STH is used in its packaged form ('sth_default.conf` file) as well as in development (`config.js` file) :)

**Comment by gtorodelvalle** [comment] 2015-06-12 08:10
In fact, as we have also discussed via Skype, it would be highly recommended to align the packaging and configuration of all the Node.js-based components and of the STH in particular with other components such as https://github.com/telefonicaid/fiware-pep-steelskin and https://github.com/telefonicaid/perseo-fe ;)

**Comment by gtorodelvalle** [comment] 2016-01-28 15:00
Closing the issue since it has already been solved once the STH code was updated to follow TID's guidelines por Node applications... ;)

**Closed by gtorodelvalle** 2016-01-28 15:00 UTC
Labels: bug, P8
